import { describe, it, expect } from '@jest/globals'
import { fireEvent, render, screen, within } from '@testing-library/react'
import { InvestigationTrailDemo } from '@/components/InvestigationTrailDemo'

describe('InvestigationTrailDemo', () => {
  it('alterna Trilha e Gráficos mantendo exercício, território e documentação aberta', () => {
    render(<InvestigationTrailDemo />)
    fireEvent.click(screen.getByRole('button', { name: /Contas públicas do Brasil/ }))
    fireEvent.change(screen.getByRole('combobox', { name: 'Exercício da investigação' }), { target: { value: '2025' } })
    fireEvent.click(within(screen.getAllByRole('article')[0]!).getByRole('button', { name: 'Documentação' }))
    fireEvent.click(screen.getByRole('tab', { name: 'Gráficos' }))
    expect(screen.getByRole('tabpanel', { name: 'Gráficos' })).toBeVisible()
    expect(screen.queryByRole('list', { name: 'Etapas da investigação' })).not.toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Contas públicas do Brasil' })).toBeInTheDocument()
    expect(screen.getByRole('combobox', { name: 'Exercício da investigação' })).toHaveValue('2025')
    expect(screen.getByText('Números fictícios · apenas para validar os gráficos')).toBeInTheDocument()
    expect(screen.getByText(/Não representam as contas de Brasil/)).toHaveTextContent('2025')
    fireEvent.click(screen.getByRole('tab', { name: 'Trilha' }))
    expect(within(screen.getAllByRole('article')[0]!).getByRole('button', { name: 'Documentação' })).toHaveAttribute('aria-expanded', 'true')
    expect(screen.getByLabelText('Quantidade de etapas')).toHaveTextContent('9 etapas')
  })

  it('destaca uma categoria e atualiza os valores fictícios conforme o exercício', () => {
    render(<InvestigationTrailDemo />)
    fireEvent.click(screen.getByRole('tab', { name: 'Gráficos' }))
    const transfers = screen.getByRole('button', { name: 'Transferências 25%' })
    fireEvent.click(transfers)
    expect(transfers).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('img', { name: /Composição fictícia da receita/ })).toHaveAccessibleName(/Transferências 25%/)
    fireEvent.change(screen.getByRole('combobox', { name: 'Exercício da investigação' }), { target: { value: '2024' } })
    expect(screen.getByRole('button', { name: 'Transferências 23%' })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('img', { name: /Evolução fictícia do saldo/ })).toHaveAccessibleName(/2024, índice 127/)
    expect(screen.getByRole('img', { name: /Evolução fictícia do saldo/ })).not.toHaveAccessibleName(/2025/)
  })

  it('restringe os gráficos ao tema e troca exemplos sem misturar categorias', () => {
    render(<InvestigationTrailDemo />)
    fireEvent.click(screen.getByRole('tab', { name: 'Gráficos' }))
    fireEvent.click(screen.getByRole('button', { name: /Quem financia a dívida de Minas/ }))
    expect(screen.getByRole('heading', { name: 'Como o saldo da dívida evolui?' })).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'De onde vem o dinheiro?' })).not.toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'Onde os recursos são aplicados?' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: /De onde vem o dinheiro de Minas/ }))
    expect(screen.getByRole('heading', { name: 'De onde vem o dinheiro?' })).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'Como o saldo da dívida evolui?' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: /Contas públicas do Brasil/ }))
    expect(screen.getByRole('button', { name: 'Receitas tributárias 64%' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Transferências/ })).not.toBeInTheDocument()
    expect(screen.getByText(/não consolidam União, Governo Geral ou setor público/)).toBeInTheDocument()
    fireEvent.click(screen.getByText('Ver valores fictícios em tabela'))
    expect(screen.getByRole('table', { name: /Índice fictício do saldo/ })).toBeInTheDocument()
  })

  it('navega entre as tabs pelo teclado', () => {
    render(<InvestigationTrailDemo />)
    const trailTab = screen.getByRole('tab', { name: 'Trilha' })
    const chartsTab = screen.getByRole('tab', { name: 'Gráficos' })
    trailTab.focus()
    fireEvent.keyDown(trailTab, { key: 'ArrowRight' })
    expect(chartsTab).toHaveFocus()
    expect(chartsTab).toHaveAttribute('aria-selected', 'true')
    expect(trailTab).toHaveAttribute('tabindex', '-1')
    fireEvent.keyDown(chartsTab, { key: 'Home' })
    expect(trailTab).toHaveFocus()
    expect(trailTab).toHaveAttribute('aria-selected', 'true')
  })

  it('encontra as contas do Brasil e troca o território, as fontes e o número de etapas', () => {
    render(<InvestigationTrailDemo />)
    fireEvent.change(screen.getByLabelText('Pergunta da investigação'), { target: { value: 'Contas públicas do Brasil' } })
    fireEvent.click(screen.getByRole('button', { name: 'Buscar exemplos' }))
    expect(screen.getByRole('heading', { name: 'Contas públicas do Brasil' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Contas públicas do Brasil/ })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByLabelText('Quantidade de etapas')).toHaveTextContent('9 etapas')
    expect(screen.getByText('Brasil', { selector: 'span' })).toBeInTheDocument()
    expect(screen.queryByText('Governo de Minas Gerais')).not.toBeInTheDocument()
    const cards = screen.getAllByRole('article')
    expect(cards).toHaveLength(9)
    expect(within(cards[1]!).getByRole('link', { name: 'Abrir fonte oficial' })).toHaveAttribute('href', 'https://portaldatransparencia.gov.br/receitas/consulta')
    fireEvent.click(within(cards[0]!).getByRole('button', { name: 'Documentação' }))
    expect(within(cards[0]!).getByText(/União, Governo Central, Governo Geral e setor público têm perímetros próprios/)).toBeInTheDocument()
    expect(within(cards[0]!).getByText('Última verificação: não executada neste protótipo.')).toBeInTheDocument()
  })

  it('mostra a simulação e muda a quantidade de etapas conforme a investigação', () => {
    render(<InvestigationTrailDemo />)
    expect(screen.getByText('Simulação para validar a experiência')).toBeInTheDocument()
    expect(within(screen.getByRole('list', { name: 'Etapas da investigação' })).getAllByRole('listitem')).toHaveLength(8)
    fireEvent.click(screen.getByRole('button', { name: /De onde vem o dinheiro de Minas/ }))
    expect(screen.getByLabelText('Quantidade de etapas')).toHaveTextContent('3 etapas')
    expect(within(screen.getByRole('list', { name: 'Etapas da investigação' })).getAllByRole('listitem')).toHaveLength(3)
    fireEvent.click(screen.getByRole('button', { name: /Quem financia a dívida de Minas/ }))
    expect(screen.getByLabelText('Quantidade de etapas')).toHaveTextContent('2 etapas')
  })

  it('abre a documentação de uma etapa posterior sem abrir as anteriores e sem inventar verificação', () => {
    render(<InvestigationTrailDemo />)
    const cards = screen.getAllByRole('article')
    fireEvent.click(within(cards[5]!).getByRole('button', { name: 'Documentação' }))
    expect(within(cards[5]!).getByRole('button', { name: 'Documentação' })).toHaveAttribute('aria-expanded', 'true')
    expect(within(cards[0]!).getByRole('button', { name: 'Documentação' })).toHaveAttribute('aria-expanded', 'false')
    expect(screen.getByText('Última verificação: não executada neste protótipo.')).toBeInTheDocument()
    expect(within(cards[5]!).getByRole('button', { name: 'Ver dados de exemplo' })).toBeDisabled()
  })

  it('mostra cobertura ausente no ano escolhido e mantém a pergunta visível', () => {
    render(<InvestigationTrailDemo />)
    fireEvent.change(screen.getByRole('combobox', { name: 'Exercício da investigação' }), { target: { value: '2025' } })
    expect(screen.getByText('Sem cobertura de exemplo para 2025. Anos disponíveis: 2023.')).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Contexto fiscal e econômico' })).toBeInTheDocument()
    expect(screen.getByText('Exemplo de lacuna: acesso ainda pendente. A pergunta permanece na trilha.')).toBeInTheDocument()
  })

  it('busca sem acento e mostra uma lacuna em vez de criar uma trilha sem correspondência', () => {
    render(<InvestigationTrailDemo />)
    fireEvent.change(screen.getByLabelText('Pergunta da investigação'), { target: { value: 'divida' } })
    fireEvent.click(screen.getByRole('button', { name: 'Buscar exemplos' }))
    expect(screen.getByRole('button', { name: /Quem financia a dívida de Minas/ })).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Pergunta da investigação'), { target: { value: 'astronomia' } })
    fireEvent.click(screen.getByRole('button', { name: 'Buscar exemplos' }))
    expect(screen.getByRole('heading', { name: 'Nenhum exemplo para esta pergunta' })).toBeInTheDocument()
    expect(screen.queryByRole('list', { name: 'Etapas da investigação' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Ver todos os exemplos' }))
    expect(screen.getByRole('list', { name: 'Etapas da investigação' })).toBeInTheDocument()
  })

  it('mostra uma prévia explicitamente ilustrativa e links para as fontes oficiais', async () => {
    render(<InvestigationTrailDemo />)
    const revenue = screen.getAllByRole('article')[0]!
    expect(within(revenue).getByRole('link', { name: 'Abrir fonte oficial' })).toHaveAttribute('href', 'https://dados.mg.gov.br/dataset/receita')
    fireEvent.click(within(revenue).getByRole('button', { name: 'Ver dados de exemplo' }))
    const dialog = await screen.findByRole('dialog')
    expect(within(dialog).getByText(/Não contém registros consultados nem valores financeiros reais/)).toBeInTheDocument()
    expect(within(dialog).getByRole('table')).toBeInTheDocument()
  })
})
